# Generated by Django 4.2.7 on 2025-07-29 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE user ADD COLUMN last_login DATETIME NULL;",
            reverse_sql="ALTER TABLE user DROP COLUMN last_login;"
        ),
    ]
